name: First one 

on: 

 workflow_dispatch:

jobs: 
 Test:
  runs-on: [ self-hosted ]
  name: testing the github
 
  steps:
   - name: Checkout git repo
     uses: actions/checkout@v2
     id: git_checkout
     
   - name: Check git version
     run: | 
      git version
      git branch
      git branch -a
